### PR TITLE
allow for multiple locations

### LINKED ISSUE #128: Extend the .withProviderClassesFrom() method to allow to specify multiple locations
### Description

Sometimes there's the need to add provider classes from multiple locations, not only from one like the default "target/classes" directory.

### Motivation

This improvement request was initially requested from @xgp during a discussion on https://keycloak-day.dev conference

### Details

_No response_

### PR DESCRIPTION
**Pull request by dasniko**
resolves #128

### CODE REVIEW

**Comment by dasniko** [comment]
@xgp Can you please have a look at this feature PR and test it with your requirements!? Thanks!

**Comment by xgp** [comment]
@dasniko I will check in the next couple of days. THANK YOU for cranking this out so quickly! :muscle:

**Comment by xgp** [comment]
@dasniko Sorry, I've been out and haven't taken care of this. Let's not let it hold up the release! I will review this later. Thanks.

**Comment by xgp** [comment]
@dasniko apologies for the looong delay. I finally tested this and it works fine.

**Comment by dasniko** [comment]
@xgp Thanks for the feedback!

**Pull request merged**
