### PR TITLE
use current thread context loader for load resources

### PR DESCRIPTION
**Pull request by gaetancollaud**
This address the first issue of #64

### CODE REVIEW

**Comment by gaetancollaud** [comment]
Wait ! Don't merge it. It seems like I've broken the tests. I will investigate.

**Comment by gaetancollaud** [comment]
I fixed the test, but the fix is kinda stupid...

**Comment by dasniko** [comment]
An alternative could be to leave it as is for now and wait for KC 18, as then the auto-import of realms is available again directly by Keycloak and I can remove my workaround with using the KC admin client/api.

**Comment by gaetancollaud** [comment]
> An alternative could be to leave it as is for now and wait for KC 18, as then the auto-import of realms is available again directly by Keycloak and I can remove my workaround with using the KC admin client/api.

Actually, if you know that you will remove this part later, it doesn't hurt to add my dirty fix. So I can go ahead with the other issue (Quarkus arc container not started).

**Pull request merged**
