### PR TITLE
Add support for mutual tls configuration

### PR DESCRIPTION
**Pull request by joshiste**
Adds support to configure the parameters needed for mutual tls (see https://www.keycloak.org/server/enabletls#_enabling_mutual_tls)

### CODE REVIEW

**Comment by dasniko** [comment]
Thanks for providing this. I made some comments to your code, please have a look at it. 🙂

**Comment by joshiste** [comment]
@dasniko sorry, but I can't find your comments on this PR. Where did you left 'em?

**Review by dasniko — CHANGES_REQUESTED** [review]

**Comment by dasniko** [comment]
Sorry, my fault. Didn't finish the review properly.

**Comment by joshiste** [comment]
@dasniko PR updated.

**Review by dasniko — APPROVED** [review]

**Pull request merged**
